### PR TITLE
Added support for configuration of report output directory in Builder and Publisher

### PR DESCRIPTION
**Pull request by mlos**
Hi Joshua,

Please consider some changes that should resolve the issue of configuring the directories where the reports are placed and read.

(https://issues.jenkins-ci.org/browse/JENKINS-18941?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20"In%20Progress"%2C%20Reopened)%20AND%20component%20%3D%20%27clang-scanbuild-plugin%27)

The issue has been bothering me a bit, so I thought I'd have a go at resolving it.

Best regards and thanks for the plugin!

Maarten

PS I forked from jenkinsci upstream, not from joshua1980, as the former was the one specified in the Jenkins plugin doc.

### CODE REVIEW

**Comment by mlos** [comment]
Fixed the tests

**Comment by mlos** [comment]
Fixed bug where folder name got expanded into Jenkins config.

**Comment by nickbroon** [comment]
+1
Can it be stored outside `$WORKSPACE`? Perhaps within /var/lib/jenkins/jobs/<jobname>/ ?
If you use something like the 'git clean after checkout' feature of the Git SCM plugin and clangScanBuildReports isn't checked into git or in the .gitignore file, or the Jenkins 'Workspace Cleanup Plugin' is used, then clangScanBuildReports in the workspace will be deleted.

**Comment by rodrigc** [comment]
Merged: https://github.com/jenkinsci/clang-scanbuild-plugin/commit/b6ceff9b1e7969cf4c830098cbc9ba06df

**Pull request closed without merging**
