### PR TITLE
Fix report html not found bug; Fix clang error bug and put build path in workspace

### PR DESCRIPTION
**Pull request by truebit**
* fix detail report not found bug when clang static analizer version >270
* fix workspace check logic error 	
* remove hard-coded "Xcode 4" 	
* add default arguments for xcodebuild and scan-build
  * `--use-analyzer Xcode` : using the 'clang' packaged with Xcode (on OS X)
  * `-derivedDataPath $WORKSPACE/build` :  save build products and other derived data to _build_ directory under current workspace
* change `build` command to `analyze`

### CODE REVIEW

**Comment by truebit** [comment]
Hi @estebanbouza ,
I have created this pull request. As I changed `build` to `analyze`, leading to serveral tests failing in jenkins.
If you use my forked hpi, I think it will not get automatic update by official.

**Comment by estebanbouza** [comment]
That's unfortunate.

I guess I'll go with the manual way and upload a compiled `hpi` out of your code.

Thanks!

**Comment by jkennedy1980** [comment]
Hey guys. Sorry I've been out of this space for a while. I'll do what I can to help you get this merged so that it can update the official plugin. This pull request has failing tests ... can we fix that?  Also, I don't have a good environment setup for this anymore so testing will be difficult. If one of you guys has a good environment I'll just grant you the ability to merge pull requests here and help me manage this project.  Thanks.

**Comment by rodrigc** [comment]
I merged this

**Pull request closed without merging**
